export default [
  { name: 'Novice', days: 1 },
  { name: 'Intermediate', days: 3 },
  { name: 'Experienced', days: 5 },
  { name: 'Expert', days: 7 },
  { name: 'Master', days: 10 },
  { name: 'Grandmaster', days: 14 },
  { name: 'Sage', days: 21 },
  { name: 'Prodigy', days: 30 },
  { name: 'Talent', days: 60 },
  { name: 'Ace', days: 90 },
  { name: 'Champion', days: 120 },
  { name: 'Icon', days: 150 },
  { name: 'Legend', days: 180 },
  { name: 'Elite', days: 240 },
  { name: 'Pro', days: 300 },
  { name: 'All-star', days: 365 },
  { name: 'Hall of Famer', days: 500 },
];
